#!/bin/bash

echo "
╔═══════════════════════════════════════════════════════════════╗
║                                                                 ║
║      📱 GUÍA VISUAL - VERIFICACIÓN EN EL NAVEGADOR             ║
║                                                                 ║
╚═══════════════════════════════════════════════════════════════╝
"

echo "🔍 PASO 1: ABRIR DEVTOOLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  macOS:          Cmd + Option + I"
echo "  Windows/Linux:  F12 o Ctrl + Shift + I"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 PASO 2: VERIFICAR CONSOLE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✅ LO QUE DEBERÍAS VER:"
echo "     Service Worker: Installing..."
echo "     Service Worker: Caching Files"
echo "     Service Worker: Activating..."
echo "     Service Worker registered successfully"
echo ""
echo "  ❌ LO QUE NO DEBERÍAS VER:"
echo "     right-arrow.png:1 Failed to load resource: 404"
echo "     fa-solid-900.woff2:1 Failed to load resource: 404"
echo "     la-solid-900.woff2:1 Failed to load resource: 404"
echo "     Uncaught TypeError: Cannot read properties of null"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🌐 PASO 3: VERIFICAR NETWORK TAB"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Ve a la pestaña 'Network' en DevTools"
echo "  2. Recarga la página (Cmd+Shift+R o Ctrl+Shift+R)"
echo "  3. Busca los siguientes archivos:"
echo ""
echo "     ✅ right-arrow.png → Status: 200 OK"
echo "     ✅ fa-solid-900.woff2 → Status: 200 OK"
echo "     ✅ fa-regular-400.woff2 → Status: 200 OK"
echo "     ✅ fa-brands-400.woff2 → Status: 200 OK"
echo "     ✅ la-solid-900.woff2 → Status: 200 OK"
echo ""
echo "  ⚠️  Puedes ignorar estos 404 (son normales):"
echo "     ❌ bootstrap.min.css.map → 404 (opcional)"
echo "     ❌ bootstrap.bundle.min.js.map → 404 (opcional)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "⚙️  PASO 4: VERIFICAR SERVICE WORKER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Ve a DevTools → Application"
echo "  2. En el menú lateral → Service Workers"
echo "  3. Verifica:"
echo ""
echo "     ✅ Source: service-worker.js"
echo "     ✅ Status: #<number> activated and is running"
echo "     ✅ Clients: Debería mostrar la página actual"
echo ""
echo "  4. Revisa el cache:"
echo "     • Application → Cache Storage"
echo "     • Busca: v2"
echo "     • Expande y verifica que incluya:"
echo "       - images/elements/right-arrow.png"
echo "       - webfonts/fa-solid-900.woff2"
echo "       - fonts/la-solid-900.woff2"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📱 PASO 5: PROBAR INSTALACIÓN PWA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Busca el botón 'Instalar App' en la página"
echo "  2. Haz click en él"
echo "  3. Debería aparecer un diálogo de instalación"
echo "  4. Click en 'Instalar'"
echo "  5. La app se abre en una nueva ventana"
echo ""
echo "  ✅ Verificaciones:"
echo "     • La app tiene su propia ventana"
echo "     • El ícono aparece en el dock/taskbar"
echo "     • La app funciona sin la barra de navegación del navegador"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔌 PASO 6: PROBAR MODO OFFLINE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. DevTools → Network Tab"
echo "  2. En la parte superior, encuentra 'Throttling'"
echo "  3. Selecciona 'Offline'"
echo "  4. Recarga la página"
echo ""
echo "  ✅ La página debería:"
echo "     • Cargar completamente"
echo "     • Mostrar todo el contenido"
echo "     • Funcionar normalmente"
echo "     • NO mostrar error de conexión"
echo ""
echo "  5. Vuelve a 'Online' cuando termines de probar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🎯 CHECKLIST FINAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Marca cada item cuando lo verifiques:"
echo ""
echo "  [ ] Console sin errores 404 críticos"
echo "  [ ] Service Worker v2 activado"
echo "  [ ] Todos los recursos cargan con 200 OK"
echo "  [ ] Cache v2 contiene nuevos archivos"
echo "  [ ] Botón 'Instalar App' visible"
echo "  [ ] Instalación PWA funciona"
echo "  [ ] Modo offline funciona correctamente"
echo "  [ ] Slider (carousel) funciona sin errores"
echo "  [ ] Iconos se muestran correctamente"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "💡 TIPS ADICIONALES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • Si ves errores antiguos, limpia el cache:"
echo "    DevTools → Application → Clear storage → Clear site data"
echo ""
echo "  • Para ver el Service Worker en acción:"
echo "    Network Tab → Marca 'Disable cache' → Recarga"
echo "    Deberías ver ⚙️ iconos indicando 'from ServiceWorker'"
echo ""
echo "  • Para forzar actualización del Service Worker:"
echo "    Application → Service Workers → 'Update'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🎉 ¡Todo listo! Si todos los checks pasan, la PWA está perfecta."
echo ""
